[build]
  command = "npm run build"
  publish = ".netlify/output/public"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "npm run dev"
  framework = "next"
  port = 3000
